version: "3"
services:
  # mail:
  #   image: schickling/mailcatcher:latest
  #   ports:
  #     - "1025:1025"
  #     - "1080:1080"
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/opt/app
      - app-bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      APP_DATABASE_HOST: mysql
      APP_DATABASE_USERNAME: root
      APP_DATABASE_PASSWORD: password
      EDITOR: vi

volumes:
  db-data:
  app-bundle:
