default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch('APP_DATABASE_HOST') { 'db' } %>
  username: <%= ENV.fetch('APP_DATABASE_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('APP_DATABASE_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: sample_development

test:
  <<: *default
  database: sample_test

staging:
  <<: *default
  database: sample_development
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: sample_production
  url: <%= ENV['DATABASE_URL'] %>
